# Generated by Django 4.0.3 on 2023-04-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessAdmin',
            fields=[
                ('Admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Mess_name', models.CharField(choices=[('1', 'FY'), ('2', 'SY'), ('3', 'TY'), ('4', 'BTech')], default=0, max_length=50)),
                ('pass1', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
    ]
