# Generated by Django 4.0.3 on 2023-04-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('messadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brekfast', models.CharField(max_length=50)),
                ('Lunch', models.CharField(max_length=50)),
                ('Dinner', models.CharField(max_length=50)),
                ('EveSnacks', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='messadmin',
            name='Mess_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.mess'),
        ),
    ]
