# Generated by Django 4.0.3 on 2023-04-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('messadmin', '0002_menu_alter_messadmin_mess_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Messname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.mess'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Notes',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
