# Generated by Django 4.0.3 on 2023-04-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0003_menu_messname_menu_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Notes',
        ),
    ]
