# Generated by Django 4.0.3 on 2023-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0006_menu_date_mealrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='bill_paid',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')], default=None),
        ),
        migrations.AddField(
            model_name='mealrecord',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=None, max_length=50),
        ),
    ]
