# Generated by Django 4.0.3 on 2023-04-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0007_mealrecord_bill_paid_mealrecord_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecord',
            name='bill_paid',
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='Meal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_paid', models.IntegerField(choices=[('0', '0'), ('1', '1')], default=None)),
                ('Meal_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='messadmin.mealrecord')),
            ],
        ),
    ]
