# Generated by Django 4.0.3 on 2023-04-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0009_rename_messname_menu_mess_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messadmin',
            old_name='Mess_name',
            new_name='Mess',
        ),
    ]
