# Generated by Django 4.0.3 on 2023-04-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_feedback_mess'),
        ('student', '0014_delete_feedback'),
        ('messadmin', '0011_rename_brekfast_menu_breakfast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BfRecord',
            fields=[
                ('Bf_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=None, max_length=50)),
                ('Messname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.mess')),
                ('Student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
