# Generated by Django 4.0.3 on 2023-04-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0012_bfrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Bf_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='messadmin.bfrecord'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_paid',
            field=models.IntegerField(default=0),
        ),
    ]
