# Generated by Django 4.0.3 on 2023-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0013_bill_bf_id_alter_bill_bill_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=None, max_length=50),
        ),
    ]
