# Generated by Django 4.0.3 on 2023-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0014_bill_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_bill',
            field=models.IntegerField(default=0),
        ),
    ]
