<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-04-13 09:26
=======
# Generated by Django 4.2 on 2023-04-13 12:08
>>>>>>> dc788d6077e11433151d9d9993202b6a9879d7ed

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0015_bill_total_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecord',
            name='mealcount',
            field=models.IntegerField(default=1),
        ),
    ]
