# Generated by Django 4.0.3 on 2023-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0015_bill_total_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecord',
            name='mealcount',
            field=models.IntegerField(default=1),
        ),
    ]
