# Generated by Django 4.0.3 on 2023-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0016_alter_mealrecord_mealcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='total_bill',
            field=models.IntegerField(default=0),
        ),
    ]
