# Generated by Django 4.0.3 on 2023-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0017_mealrecord_total_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='bill_paid',
            field=models.IntegerField(default=0),
        ),
    ]
