# Generated by Django 4.0.3 on 2023-05-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0018_mealrecord_bill_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecord',
            name='bill_paid',
        ),
        migrations.RemoveField(
            model_name='mealrecord',
            name='total_bill',
        ),
    ]
