# Generated by Django 4.0.3 on 2023-05-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_delete_feedback'),
        ('messadmin', '0019_remove_mealrecord_bill_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Bf_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Meal_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='Student_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
