# Generated by Django 4.0.3 on 2023-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('Mess_name', models.CharField(choices=[('1', 'FY'), ('2', 'SY'), ('3', 'TY'), ('4', 'BTech')], default=None, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
