# Generated by Django 4.0.3 on 2023-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='Mess_name',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('BTech', 'BTech')], default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
