# Generated by Django 4.0.3 on 2023-04-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Mess',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.mess'),
        ),
    ]
