# Generated by Django 4.0.3 on 2023-05-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_delete_feedback'),
        ('administrator', '0005_alter_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_id', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=None, max_length=50)),
                ('Mess', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.mess')),
                ('Student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
