# Generated by Django 4.0.3 on 2023-05-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Mess',
        ),
    ]
