# Generated by Django 4.0.3 on 2023-05-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Mess',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.mess'),
        ),
    ]
