# Generated by Django 4.0.3 on 2023-05-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_remove_transaction_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unpaid_bill',
            field=models.IntegerField(default=0),
        ),
    ]
