# Generated by Django 4.0.3 on 2023-05-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_transaction_unpaid_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='unpaid_bill',
            new_name='paid_bill',
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_bill',
            field=models.IntegerField(default=0),
        ),
    ]
