# Generated by Django 4.0.3 on 2023-05-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_rename_unpaid_bill_transaction_paid_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paid_bill',
            new_name='unpaid_bill',
        ),
    ]
