# Generated by Django 4.0.3 on 2023-04-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='MessEnrolled',
            field=models.CharField(choices=[('1', 'FY'), ('2', 'SY'), ('3', 'TY'), ('4', 'BTech')], default='', max_length=70),
        ),
    ]
