# Generated by Django 4.2 on 2023-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='MessEnrolled',
            field=models.CharField(choices=[('1', 'FY'), ('2', 'SY'), ('3', 'TY'), ('4', 'BTech')], default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None),
        ),
    ]
