# Generated by Django 4.0.3 on 2023-04-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_gender_alter_student_messenrolled_and_more'),
        ('student', '0003_alter_student_gender_alter_student_year'),
    ]

    operations = [
    ]
