# Generated by Django 4.0.3 on 2023-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='MessEnrolled',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('BTech', 'BTech')], default='', max_length=70),
        ),
    ]
