# Generated by Django 4.0.3 on 2023-04-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_gender_alter_student_messenrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='MessEnrolled',
            new_name='Mess',
        ),
    ]
