# Generated by Django 4.0.3 on 2023-04-08 12:32

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_messenrolled_student_mess'),
    ]

    operations = [
    migrations.AddField(
        model_name='student',
        name='Mess',
        field=models.CharField(max_length=50, null=True, blank=True),
    ),
]

