# Generated by Django 4.0.3 on 2023-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_add_mess_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mess',
            field=models.CharField(default='', max_length=20),
        ),
    ]
