# Generated by Django 4.0.3 on 2023-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mess',
            field=models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('BTech', 'BTech')], default='', max_length=20),
        ),
    ]
