# Generated by Django 4.0.3 on 2023-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_mess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]),
        ),
    ]
