# Generated by Django 4.2 on 2023-04-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_year'),
    ]

    operations = [
    ]
