# Generated by Django 4.2 on 2023-04-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_student_year'),
        ('student', '0012_auto_20230408_1415'),
    ]

    operations = [
    ]
